language: minimal

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - PACKAGE_VCS_URL=https://gitlab.com/aursu/rpmbuild-libtool.git
    - BINTRAY_REPO=custom
  jobs:
    - BASE=centos7base BUILD=centos7build UPLOADER=centos7bintray

install:
  - docker-compose -f docker-compose.base.yml build --no-cache --pull ${BASE}

before_script:
  - docker-compose build --no-cache ${BUILD}

script:
  - docker-compose up --exit-code-from ${BUILD} ${BUILD}

before_deploy:
  - docker-compose -f rpmbuild/docker-compose.bintray.yml pull ${UPLOADER}

deploy:
  provider: script
  script: docker-compose -f rpmbuild/docker-compose.bintray.yml run --rm -e BINTRAY_USER=$BINTRAY_USER -e BINTRAY_API_KEY=$BINTRAY_API_KEY -e BINTRAY_REPO=$BINTRAY_REPO -e PACKAGE_VCS_URL=$PACKAGE_VCS_URL ${UPLOADER}
  on:
    all_branches: true

# https://docs.travis-ci.com/user/build-matrix/#explicitly-included-jobs-with-only-one-element-in-the-build-matrix
jobs:
  include:
    - stage: deploy
      install: skip
      before_script: skip
      script:
        - docker-compose -f build/docker-compose.yml build --no-cache --pull
      before_deploy:
        - docker login -u $DOCKER_USER -p $DOCKER_PASS
      deploy:
        provider: script
        script: docker-compose -f build/docker-compose.yml push
        on:
          all_branches: true